agents:
  image: "docker.elastic.co/appex-qa/qaf:latest@sha256:eb101d3387e8e99145db5a2c0bff8700100c7c3a9f1caf9a1b998b737bdb1a4b"
  memory: "3G"

env:
  EC_REGISTER_BACKEND: "appex-qa-team-cluster"
  EC_REGION: "gcp-us-central1"
  EC_ENV: "qa"
  EC_DEPLOYMENT_NAME: "bk-ess-security-geneve-${BUILDKITE_BUILD_NUMBER}"

steps:
  - label: ":pipeline: Create environment `ess-geneve-test-environment`"
    key: create_geneve_environment
    command:
      - "qaf elastic-cloud deployments create"

  - label: ":rocket: Deploy Geneve tests"
    key: geneve_tests
    depends_on: create_geneve_environment
    command:
      - python3 -m pip install -r requirements.txt
      - ./scripts/test-stacks.sh qaf-ess ${TEST_EXTRA_PARAMS:---online -v --queries}

  - label: ":pipeline: Delete environment `serverless-geneve-test-environment`"
    key: delete_geneve_environment
    depends_on:
      - create_geneve_environment
      - geneve_tests
    command:
      - "qaf elastic-cloud deployments remove"
      - "qaf elastic-cloud deployments list || true"
    allow_dependency_failure: true
