agents:
  image: "docker.elastic.co/appex-qa/qaf:latest@sha256:4ef94d08272b5d3fab80ecfc3efacad0ad88f76ca1dafb4d0b746c710864b4ca"
  memory: "3G"

env:
  EC_REGISTER_BACKEND: "appex-qa-team-cluster"
  EC_REGION: "gcp-us-central1"
  EC_ENV: "qa"
  EC_DEPLOYMENT_NAME: "bk-ess-security-geneve-${BUILDKITE_BUILD_NUMBER}"
  STACK_VERSION_DEFAULT: "9.2.0"

steps:
  - label: ":pipeline: Create environment `ess-geneve-test-environment`"
    key: create_geneve_environment
    command:
      - "export STACK_VERSION=$${STACK_VERSION:-$STACK_VERSION_DEFAULT}"
      - "qaf elastic-cloud deployments create"

  - label: ":rocket: Deploy Geneve tests"
    key: geneve_tests
    depends_on: create_geneve_environment
    command:
      - echo "~~~ Install dependencies"
      - python3 -m pip install -r requirements.txt
      - echo "+++ Run tests"
      - ./scripts/test-stacks.sh qaf-ess ${TEST_EXTRA_PARAMS:---online -v --queries}
    artifact_paths:
      - tests/reports/*.new.md

  - label: ":pipeline: Delete environment `serverless-geneve-test-environment`"
    key: delete_geneve_environment
    depends_on:
      - create_geneve_environment
      - geneve_tests
    command:
      - "qaf elastic-cloud deployments remove"
      - "qaf elastic-cloud deployments list || true"
    allow_dependency_failure: true
