---
# $yaml-language-server: $schema=https://raw.githubusercontent.com/buildkite/pipeline-schema/main/schema.json
steps:
  - label: "Execute main pipeline"
    plugins:
      monorepo-diff#v1.5.0:
        diff: ".buildkite/diff ${BUILDKITE_COMMIT}"
        wait: true
        watch:
          # if our Renovate configuration is amended, then make sure we have well-formed config
          # for more info, see https://docs.elastic.dev/plat-prod-team/service-catalogue/renovate/testing-renovate-changes
          - path: "renovate.json"
            config:
              label: "Verify Renovate configuration"
              command: "renovate-config-validator"
              agents:
                image: "docker.elastic.co/ci-agent-images/pipelib:0.17.0@sha256:1c479a2214f39a4857983daac707d1f4166b08d578a795d9b3e5def834b54457"
          # if our catalog-info.yaml is changed, make sure it's well-formed according to our internal standards as well as Backstage's validation
          - path: "catalog-info.yaml"
            config:
              command: "/agent/check-catalog-info.sh"
              agents:
                image: "docker.elastic.co/ci-agent-images/pipelib:0.17.0@sha256:1c479a2214f39a4857983daac707d1f4166b08d578a795d9b3e5def834b54457"
          - default:
              config:
                label: "Upload test pipeline"
                command: "buildkite-agent pipeline upload .buildkite/pipelines/test.yml"
