agents:
  image: "docker.elastic.co/appex-qa/qaf:latest@sha256:41ba48654adbf4cd336051d4c81210dedde3ba9f7c12efca108c60bff556aeb0"
  memory: "3G"

env:
  EC_REGISTER_BACKEND: "appex-qa-team-cluster"
  EC_REGION: "aws-eu-west-1"
  EC_ENV: "qa"
  EC_PROJECT_NAME: "bk-serverless-security-geneve-${BUILDKITE_BUILD_NUMBER}"
  EC_PROJECT_TYPE: "security"

steps:
  - label: ":pipeline: Create environment `serverless-geneve-test-environment`"
    key: create_geneve_environment
    command:
      - "qaf elastic-cloud projects create"

  - label: ":rocket: Deploy Geneve quality gate"
    key: geneve_quality_gate
    depends_on: create_geneve_environment
    command:
      - python3 -m pip install -r requirements.txt
      - ./scripts/test-stacks.sh qaf-serverless ${TEST_EXTRA_PARAMS:---online -v --queries}

  - label: ":pipeline: Delete environment `serverless-geneve-test-environment`"
    key: delete_geneve_environment
    depends_on:
      - create_geneve_environment
      - geneve_quality_gate
    command:
      - "qaf elastic-cloud projects delete"
      - "qaf elastic-cloud projects list || true"
    allow_dependency_failure: true
