---
steps:
  - label: "Trig Serverless Security QG with pre-built rules"
    trigger: "geneve-serverless-security-quality-gate"
    build:
      branch: "$BUILDKITE_BRANCH"
      commit: "$BUILDKITE_COMMIT"
      message: "$BUILDKITE_MESSAGE"
      env:
        TEST_EXTRA_PARAMS: "--online"
        TEST_VERBOSITY: 2
